const express=require('express')
const app =express()
require('./config/db')
const dotenv = require('dotenv')
const userrouter = require('./router/user.router')
const cors =require('cors')
const blogrouter = require('./router/blog.router')
app.use(cors())
dotenv.config()
app.use(express.json())

app.use(userrouter)
app.use(blogrouter)
app.listen(process.env.port,()=>console.log(`server is running ${process.env.port}`))